# Generated by Django 4.1.7 on 2023-05-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verified',
            field=models.CharField(choices=[('unverified', 'unverified'), ('teacher', 'teacher'), ('verified', 'verified'), ('admin', 'admin')], default='unverified', max_length=10),
        ),
    ]
